#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'
open-port $(config-get http_port)
open-port $(config-get pb_port)
